pipelines:
  branches:
    master:
      - step:
          name: Push to GitHub Repository
          script:
            - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/mailblaze/mailblaze-wp.git
            - git push github master
          services:
            - docker